/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SellerProdukImport } from './routes/seller/produk'
import { Route as SellerPesananImport } from './routes/seller/pesanan'
import { Route as SellerPengaturanImport } from './routes/seller/pengaturan'
import { Route as SellerDashboardImport } from './routes/seller/dashboard'
import { Route as SellerAturTokoImport } from './routes/seller/atur-toko'
import { Route as SellerAddProductImport } from './routes/seller/add-product'
import { Route as BuyerDetailOrderImport } from './routes/buyer/detail-order'
import { Route as BuyerDashboardImport } from './routes/buyer/dashboard'
import { Route as BuyerCheckoutImport } from './routes/buyer/checkout'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SellerProdukRoute = SellerProdukImport.update({
  path: '/seller/produk',
  getParentRoute: () => rootRoute,
} as any)

const SellerPesananRoute = SellerPesananImport.update({
  path: '/seller/pesanan',
  getParentRoute: () => rootRoute,
} as any)

const SellerPengaturanRoute = SellerPengaturanImport.update({
  path: '/seller/pengaturan',
  getParentRoute: () => rootRoute,
} as any)

const SellerDashboardRoute = SellerDashboardImport.update({
  path: '/seller/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const SellerAturTokoRoute = SellerAturTokoImport.update({
  path: '/seller/atur-toko',
  getParentRoute: () => rootRoute,
} as any)

const SellerAddProductRoute = SellerAddProductImport.update({
  path: '/seller/add-product',
  getParentRoute: () => rootRoute,
} as any)

const BuyerDetailOrderRoute = BuyerDetailOrderImport.update({
  path: '/buyer/detail-order',
  getParentRoute: () => rootRoute,
} as any)

const BuyerDashboardRoute = BuyerDashboardImport.update({
  path: '/buyer/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BuyerCheckoutRoute = BuyerCheckoutImport.update({
  path: '/buyer/checkout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/buyer/checkout': {
      id: '/buyer/checkout'
      path: '/buyer/checkout'
      fullPath: '/buyer/checkout'
      preLoaderRoute: typeof BuyerCheckoutImport
      parentRoute: typeof rootRoute
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardImport
      parentRoute: typeof rootRoute
    }
    '/buyer/detail-order': {
      id: '/buyer/detail-order'
      path: '/buyer/detail-order'
      fullPath: '/buyer/detail-order'
      preLoaderRoute: typeof BuyerDetailOrderImport
      parentRoute: typeof rootRoute
    }
    '/seller/add-product': {
      id: '/seller/add-product'
      path: '/seller/add-product'
      fullPath: '/seller/add-product'
      preLoaderRoute: typeof SellerAddProductImport
      parentRoute: typeof rootRoute
    }
    '/seller/atur-toko': {
      id: '/seller/atur-toko'
      path: '/seller/atur-toko'
      fullPath: '/seller/atur-toko'
      preLoaderRoute: typeof SellerAturTokoImport
      parentRoute: typeof rootRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardImport
      parentRoute: typeof rootRoute
    }
    '/seller/pengaturan': {
      id: '/seller/pengaturan'
      path: '/seller/pengaturan'
      fullPath: '/seller/pengaturan'
      preLoaderRoute: typeof SellerPengaturanImport
      parentRoute: typeof rootRoute
    }
    '/seller/pesanan': {
      id: '/seller/pesanan'
      path: '/seller/pesanan'
      fullPath: '/seller/pesanan'
      preLoaderRoute: typeof SellerPesananImport
      parentRoute: typeof rootRoute
    }
    '/seller/produk': {
      id: '/seller/produk'
      path: '/seller/produk'
      fullPath: '/seller/produk'
      preLoaderRoute: typeof SellerProdukImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AdminDashboardRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
  BuyerCheckoutRoute,
  BuyerDashboardRoute,
  BuyerDetailOrderRoute,
  SellerAddProductRoute,
  SellerAturTokoRoute,
  SellerDashboardRoute,
  SellerPengaturanRoute,
  SellerPesananRoute,
  SellerProdukRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin/dashboard",
        "/auth/login",
        "/auth/register",
        "/buyer/checkout",
        "/buyer/dashboard",
        "/buyer/detail-order",
        "/seller/add-product",
        "/seller/atur-toko",
        "/seller/dashboard",
        "/seller/pengaturan",
        "/seller/pesanan",
        "/seller/produk"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/buyer/checkout": {
      "filePath": "buyer/checkout.tsx"
    },
    "/buyer/dashboard": {
      "filePath": "buyer/dashboard.tsx"
    },
    "/buyer/detail-order": {
      "filePath": "buyer/detail-order.tsx"
    },
    "/seller/add-product": {
      "filePath": "seller/add-product.tsx"
    },
    "/seller/atur-toko": {
      "filePath": "seller/atur-toko.tsx"
    },
    "/seller/dashboard": {
      "filePath": "seller/dashboard.tsx"
    },
    "/seller/pengaturan": {
      "filePath": "seller/pengaturan.tsx"
    },
    "/seller/pesanan": {
      "filePath": "seller/pesanan.tsx"
    },
    "/seller/produk": {
      "filePath": "seller/produk.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
